# Generated by Django 5.2 on 2025-05-09 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quake", "0004_history_delete_searchhistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="keyword",
        ),
        migrations.AddField(
            model_name="history",
            name="end_year",
            field=models.IntegerField(default=2002),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="max_magnitude",
            field=models.FloatField(default=8.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="min_magnitude",
            field=models.FloatField(default=2.6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="prefecture",
            field=models.CharField(
                default={"maxlat": 46, "maxlon": 150, "minlat": 20, "minlon": 122},
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="history",
            name="start_year",
            field=models.IntegerField(default=2002),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="history",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
