# Generated by Django 5.2.8 on 2026-09-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quake', '0005_remove_history_keyword_history_end_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Earthquake',
        ),
        migrations.AlterField(
            model_name='history',
            name='prefecture',
            field=models.CharField(max_length=30),
        ),
    ]
